config/routes.rb
Partiude::Application.routes.draw do
  root :to => 'index#index'

  devise_for :users, :path_names => { :sign_in => 'login',
                                      :sign_out => 'logout',
                                      :password => 'recover_password' }

  resources :itineraries, :except => :edit do
    get "search", :on => :collection
  end

  resources :polls, :only => [:create, :view] do
    post "vote", :on => :member
  end

  resources :users, :only => :show
end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base

  attr_accessible :name, :transport_type, :origin, :destiny,
                  :day, :hour, :repeat_in, :user, :recurring,
                  :participants, :recurring_attributes

  has_many :points
  has_many :participants
  has_many :users, :through => :participants
  has_many :comments
  has_many :polls, :dependent => :destroy
  has_many :requestors, :through => :polls

  has_one :recurring, :dependent => :destroy

  has_enumeration_for :transport_type, :create_scopes => true, :create_helpers => {:prefix => true}
  has_enumeration_for :state, :create_scopes => true, :create_helpers => true

  accepts_nested_attributes_for :points, :allow_destroy => true
  accepts_nested_attributes_for :participants, :allow_destroy => true
  accepts_nested_attributes_for :recurring, :allow_destroy => true

  validates_presence_of :name
  validates_presence_of :origin
  validates_presence_of :destiny
  validates_presence_of :transport_type
  validates_presence_of :recurring

  validate :check_origin_and_destiny_address, :on => :create
  validates_length_of :participants, :minimum => 1, :allow_nil => false
  validates_length_of :participants, :maximum => 5, :if => :transport_type_car?

  validate :check_driver, :if => :transport_type_car?

  def origin_coordinates
    coordinations_for(origin) if origin.present?
  end

  def destiny_coordinates
    coordinations_for(origin) if destiny.present?
  end

  def add_participant(user)
    participants << Participant.new(:itinerary => self, :user => user)
  end

  def prepare
    build_recurring unless recurring.present?
  end

  def already_participating?(user)
    users.include? user
  end

  def has_pending_poll_for?(user)
    Poll.active.where(:requestor_id => user.id, :itinerary_id => self.id).size > 0
  end

  def self.visible_to(user)
    Itinerary.joins(:participants).where(:"participants.user_id" => user.id)
  end

private
  def check_origin_and_destiny_address
    errors.add(:origin, :invalid_address) unless origin_coordinates.present?
    errors.add(:destiny, :invalid_address) unless destiny_coordinates.present?
  end

  def coordinations_for(address)
    coordination = Geocoder.search(address)[0]
    [coordination.latitude, coordination.longitude] if coordination.present?
  end

  def check_driver
    if participants.size >= 5 && !has_a_driver?
      errors.add(:participants, :need_a_driver)
    end
  end

  def has_a_driver?
    participants.select do |participant|
      participant.driver?
    end.size > 0
  end

end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController

  def index
    @itinerary = Itinerary.new(:recurring => Recurring.new)
    @itineraries = Itinerary.visible_to(current_user).order("updated_at desc")
  end

  def new
    @itinerary = Itinerary.new(:recurring => Recurring.new)
    @itinerary.add_participant(current_user)
  end

  def create
    @itinerary = Itinerary.active.new
    @itinerary.prepare
    @itinerary.attributes = params[:itinerary]

    @itinerary.add_participant(current_user)
    respond_to do |format|
      if @itinerary.save
        format.html { redirect_to itineraries_path, :notice => I18n.t(:"alerts.successfully_created", :model => Itinerary.model_name.human) }
        format.js
      else
        format.html { render "_form" }
        format.js
      end
    end
  end

  def show
    @itinerary = Itinerary.find(params[:id])
    @polls = Poll.for(@itinerary, current_user)
    respond_with @itinerary
  end

  def search
    @itinerary = Itinerary.new(:recurring => Recurring.new)
    if params[:itinerary].present?
      params[:itinerary][:current_user] = current_user
      @itineraries = ItinerarySearch.search(params[:itinerary])
    end
    respond_with @itineraries
  end

end

app/helpers/itineraries_helper.rb
module ItinerariesHelper

  def transport_type_img(transport_type)
    case transport_type
      when TransportType::CAR
        image_tag("balao-carro.png", :style => "float:left;")
      when TransportType::BIKE
        image_tag("balao-bicicleta.png", :style => "float:left;")
      when TransportType::WALK
        image_tag("balao-ape.png", :style => "float:left;")
    end
  end

  def show_participants(itinerary)
    participants = itinerary.participants
    group_size_greeting(participants)
  end

  def join_modal
    if !@itinerary.already_participating?(current_user) && @itinerary.has_pending_poll_for?(current_user)
      modal_button I18n.t(:"itinerary.join"), "join-modal", :class=>"radius button"
    end
  end

  def repeat_in_humanize(recurring)
    content = content_tag('span', recurring.repeat_in_humanize)
    if recurring.repeat_in_weekly? or recurring.repeat_in_monthly?
      content += content_tag("br")
      content += content_tag('span', recurring.repeation_days.collect { |day| DaysOfWeek.t(day.to_s) }.join(", "))
    end
    content
  end

private
  def participants_thumb(participants)
  end

  def group_size_greeting(participants)
    if participants.present?
      if participants.size > 1
        I18n.t("itinerary.has_many".to_sym, participants.size)
      else
        I18n.t("itinerary.has_one".to_sym)
      end
    else
      I18n.t("itinerary.has_none".to_sym)
    end
  end

end

app/views/itineraries/_form.html.erb
<div class="twelve columns ">
  <%= form_for(@itinerary, :builder => ItineraryFormBuilder, :remote => true, :html => {:class => "custom"}) do |f| %>
    <fieldset>
      <legend><%= "#{I18n.t(:new)} #{Itinerary.model_name.human}" %></legend>
      <%= render :partial => 'shared/form_alerts', :locals => { :entity => @itinerary } %>
      <%= f.text_field :name, :class => "radius twelve", :placeholder=>"#{Itinerary.human_attribute_name(:name)}" %>
      <div class="row">
        <%= f.transport_type_field %>
      </div>  
      <div class="row">
        <div class="six columns">
          <%= f.text_field :origin, :class => "radius twelve", :placeholder=>"#{Itinerary.human_attribute_name(:origin)}" %>
        </div>
        <div class="six columns">
          <%= f.text_field :destiny, :class => "radius twelve", :placeholder=>"#{Itinerary.human_attribute_name(:destiny)}" %>
        </div>
      </div>  
      <div class="row">
        <%= render :partial => "itineraries/form_recurring", :locals => { :recurring => @itinerary.recurring, :nested_form => f } %>
      </div>
      <%= f.submit :class=>"radius button four offset-by-eight", :value=>"#{I18n.t(:create)}" %>
    </fieldset>
  <% end %>
</div>

<% content_for :js do %>
  <%= javascript_include_tag "itinerary.form.js" %>
<% end %>

app/views/itineraries/_form_recurring.html.erb
<% p recurring %>
<%= nested_form.fields_for(:recurring_attributes, recurring, :builder => RecurringFormBuilder) do |f| %>
  <div class="row">
    <%= f.repeat_in_field %>
    <div class="six columns">
      <%= f.text_field :hour, :class => "radius twelve timepicker", :placeholder=>"#{Recurring.human_attribute_name(:hour)}" %>
    </div>
  </div>
  <div class="row">
    <div class="six columns">
      <%= f.text_field :begin_day, :value => I18n.l(Date.today), :class => "radius twelve datepicker invisible", :placeholder=>"#{Recurring.human_attribute_name(:begin_day)}" %>
    </div>
    <div class="six columns">
      <%= f.day_of_week_check_box(:sunday) %>
      <%= f.day_of_week_check_box(:monday) %>
      <%= f.day_of_week_check_box(:tuesday) %>
      <%= f.day_of_week_check_box(:wednesday) %>
      <%= f.day_of_week_check_box(:thursday) %>
      <%= f.day_of_week_check_box(:friday) %>
      <%= f.day_of_week_check_box(:saturday) %>
    </div>
  </div>
<% end %>

app/views/itineraries/_itinerary.html.erb
<div class="itinerary-container">
  <div class="itinerary-group row">
    <div class=" twelve columns ">
      <div class="row">
        <div class="twelve columns itinerary-header">
          <%= transport_type_img(itinerary.transport_type) %>
          <h3 class="columns subheader"><%= itinerary.name %></h3>
          <div class="one column end">
            <a href="#"><%= image_tag "status-aguardando.png" %></a>
          </div>
          <div class="itinerary-buttons two columns">
            <!--<a href="#" class="radius button"><%= I18n.t("itinerary.similars".to_sym) %></a>-->
            <%= link_to(I18n.t("itinerary.view".to_sym), itinerary, :class => "radius button") %>
        </div>
        </div>
      </div>
      <div class="itinerary-group-info row">
            <div class="three columns">
              <div class="icon-origin description-marker"></div>
              <p><strong>Origem</strong></p>
              <p><%= itinerary.origin %></p>
            </div>
          <div class="three columns">
              <div class=" description-marker icon-destiny "></div>
              <p><strong>Destino</strong></p>
              <p><%= itinerary.destiny %></p>
          </div>
          <div class="six columns">
            <%= render :partial => 'itineraries/recurring', :locals => {:recurring => itinerary.recurring} %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/itineraries/_join.html.erb
<% if !itinerary.already_participating?(current_user) %>
  <div id="join-modal" data-closeOnBackgroundClick="true" class="reveal-modal medium">
    <h2><%= I18n.t(:"itinerary.join_modal.header") %></h2>
    <p class="lead">
      <%= I18n.t(:"itinerary.join_modal.body") %>
    </p>
    <%= form_tag(polls_path, :remote => true, :class => "custom", :method => :post) do %>
      <%= fields_for :poll do |poll| %>
        <%= label_tag :origin, Poll.human_attribute_name(:origin) %>
        <%= poll.text_field :origin %>
        <%= label_tag :destiny, Poll.human_attribute_name(:destiny) %>
        <%= poll.text_field :destiny %>
        <%= poll.hidden_field :itinerary_id, :value => itinerary.id %>
      <% end %>
      <%= submit_tag I18n.t(:"itinerary.join"), :class=>"radius button" %>
    <% end %>
    <a class="close-reveal-modal">&#215;</a>
  </div>
<% end %>

app/views/itineraries/_participants.html.erb
<div class="group-users">
  <h6><%= Itinerary.human_attribute_name(:participants) %></h6>
  <div class="users">
    <% @itinerary.participants.each do |participant| %>
      <%= render :partial => "shared/participant_thumb_large", :locals => {:participant => participant} %>
    <% end %>
  </div>
</div>

app/views/itineraries/_pending_polls.html.erb
<% polls.each do |poll| %>
  <%= render :partial => "polls/poll_widget", :locals => {:poll => poll} %>
<% end %>

app/views/itineraries/_recurring.html.erb
<div class="left"><%= image_tag "icone-calendar.png" %></div>
<div class="six columns">
  <p><strong><%= recurring.repeat_in_humanize %></strong></p>
  <p><%= I18n.t(:"recurring.when_it_happen", :date => I18n.l(recurring.start), :days => recurring.repeation_days.collect { |day| DaysOfWeek.t(day.to_s) }.join(", ")) %></p>
</div>
<div class="four columns">
  <p><%= I18n.t(:"recurring.and_reocurr_than", :date => I18n.l(recurring.next_occur)) %></p>
</div>

app/views/itineraries/create.js.erb
<% if @itinerary.errors.present? %>
  $("#add-itinerary-fieldset").find("div.alert").remove();
  var errors = '<%= j render(:partial => 'shared/form_alerts', :locals => {:entity => @itinerary}) %>';
  $("#add-itinerary-fieldset").prepend(errors);
<% else %>
  var newItinerary = '<%= j render(@itinerary) %>';
  $("div.itineraries-list").prepend(newItinerary);
  <% @itinerary = Itinerary.new(:recurring => Recurring.new) %>
  $("div.itineraries-form").html("<%= j render(:partial => 'itineraries/form') %>");
  new RecurringSelector($("#recurring_repeat_in")).loadFields();
  $(document).foundationCustomForms();
<% end %>

app/views/itineraries/index.html.erb
<div class="margin-content"> 
	<div class="itineraries-header">
		<div class="row">
			<div class="four columns centered">
				<h3>Não encontrou um trajeto similar ao seu?</h3>
				<p>Cadastre o seu trajeto para encontrar outras pessoas e compartilhar essa experiência.</p>
				<%= link_to(I18n.t("itinerary.new".to_sym), new_itinerary_path, :class => "button radius secondary") %>
			</div>
		</div>
</div>
	<div class="itineraries-list row">
	  <%= render(@itineraries) %>
	</div>
</div>

app/views/itineraries/join.js.erb
var form = $("#location_point").parent();
<% if @poll.errors.present? %>
  $(form).find("div.alert").remove();
  $(form).prepend("<%= j render(:partial => 'shared/form_alerts', :locals => { :entity => @poll }) %>");
<% else %>
  $("#join-modal").trigger("reveal:close");
<% end %>

app/views/itineraries/new.html.erb
<div class="margin-content">
	<div class="row">
	  <div class="four columns">
	    <h4>Permita que outras pessoas compartilhem o trajeto com você! </h4>
	    <p>Preencha o formulário com os dados do trajeto que gostaria de compartilhar.</p>
	    	<p>Lembre-se de buscar trajetos similares antes de criar um novo, é possível que já existam grupos com o mesmo objetivo que você!</p>
	  </div>
	  <div class="eight columns">
			<%= render :partial => "itineraries/form" %>
		</div>
	</div>
</div>

app/views/itineraries/search.html.erb
<div class="margin-content">
  <div class="row">
    <div class="nine columns offset-by-one end">
      <h3>Encontre aqui um grupo para compartilhar o seu trajeto!</h3>
      <p>Preencha o formulário com os dados do trajeto que gostaria de compartilhar, procuraremos grupos com trajetos similares aos seu! </p>
      <p>Lembre-se, você pode não encontrar um trajeto igual ao seu, porém um bastante similar!</p>
    </div>
  </div>
  <div class="row">
    <div class="ten columns centered">
      <%= form_for(@itinerary, :url => search_itineraries_path, :builder => ItineraryFormBuilder,
                    :remote => true, :method => :get, :target => :results,
                    :html => {:class => "custom"}) do |f| %>
     <%= render :partial => 'shared/form_alerts', :locals => { :entity => @itinerary } %>
      <div class="row">
        <%= f.transport_type_field %>
      </div>  
      <div class="row">
        <div class="six columns">
          <%= f.text_field :origin, :class => "radius twelve", :placeholder=>"#{Itinerary.human_attribute_name(:origin)}" %>
        </div>
        <div class="six columns">
          <%= f.text_field :destiny, :class => "radius twelve", :placeholder=>"#{Itinerary.human_attribute_name(:destiny)}" %>
        </div>
      </div>  
      <div class="row">
        <%= render :partial => "itineraries/form_recurring", :locals => { :recurring => @itinerary.recurring, :nested_form => f } %>
      </div>
          <div class="row"> 
            <div class="four columns offset-by-eight">
              <%= f.submit I18n.t(:search), :remote => true, :class=>"radius button twelve" %> 
            </div>
          </div>
      <% end %>
    </div>
  </div>
  <div class="twelve columns" id="results">
  </div>

    <% content_for :js do %>
      <%= javascript_include_tag "itinerary.form.js" %>
    <% end %>
</div>

app/views/itineraries/search.js.erb
<%= render 'shared/results' %>

app/views/itineraries/show.html.erb
<div class="itinerary-map"
	  data-origin-coordiation="<%= @itinerary.origin_coordinates %>"
	  data-destiny-coordiation="<%= @itinerary.destiny_coordinates %>"
	  data-origin="<%= @itinerary.origin %>"
	  data-destiny="<%= @itinerary.destiny %>">
</div>
<div class="row">
	<div class="eight columns">
		<% if @itinerary.already_participating?(current_user) %>
			<div class="row">
					<%= render :partial => "itineraries/pending_polls", :locals => {:polls => @polls} %>
			</div>
		<% end %>
		<div class="row">
			#coments e info do user
		</div>
	</div>
	<div class="four columns group-sidebar">
		<div class="row">
			<%= join_modal %>
		</div>
		<div class="row">
			<div class="twelve columns">
				<div class="icon-origin description-marker"></div>
				<div class="nine columns">
					<h6><%= Itinerary.human_attribute_name(:origin) %></h6>
					<p><%= @itinerary.origin %></p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="twelve columns">
				<div class="icon-destiny description-marker"></div>
				<div class="nine columns">
					<h6><%= Itinerary.human_attribute_name(:destiny) %></h6>
					<p> <%= @itinerary.destiny %></p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="twelve columns">
				<div class="group-recurrency"><%= image_tag "icone-calendar.png" %></div>
				<h6><%= I18n.t(:"recurring.when") %></h6>
				<p>
					<%= repeat_in_humanize(@itinerary.recurring) %>
				</p>
			</div>
		</div>
		<div class="row">
			<div class="twelve columns">
				<div class="group-recurrency"><%= image_tag "icon-clock.png" %></div>
				<h6><%= I18n.t(:"recurring.at") %></h6>
				<p> <%= @itinerary.recurring.hour %></p>
			</div>
		</div>
		<div class="row">
			<div class="twelve columns">
				<h6><%= I18n.t(:"recurring.when_started") %></h6>
				<p> <%= I18n.l(@itinerary.recurring.begin_day, :format => :no_time) %></p>
			</div>
		</div>
		<div class="row">
			<div class="twelve columns">
				<%= render :partial => "itineraries/participants" %>
			</div>
		</div>
	</div>
</div>

<%= render :partial => 'itineraries/join', :locals => { :itinerary => @itinerary } %>

<% content_for :js do %>
<script type="text/javascript">
  var itineraryMap = $("div.itinerary-map")[0];
  new ItineraryMap(itineraryMap).render();
</script>
<% end %>