config/routes.rb
Partiude::Application.routes.draw do
  root :to => 'index#index'

  devise_for :users, :path_names => { :sign_in => 'login',
                                      :sign_out => 'logout',
                                      :password => 'recover_password' }

  resources :itineraries, :except => :edit do
    get "search", :on => :collection
  end

  resources :polls, :only => [:create, :view] do
    post "vote", :on => :member
  end

  resources :users, :only => :show
end

app/views/shared/_form_alerts.html.erb
<% if entity.errors.any? %>
  <div class="alert-box alert">
      <p>
        <strong><%= pluralize(entity.errors.count, (t :"activerecord.errors.messages.one"), (t :"activerecord.errors.messages.other")) %> </strong>
      </p>

      <ul>
        <% entity.errors.full_messages.each do |msg| %>
            <li style="list-style:inside"><%= msg %></li>
        <% end %>
      </ul>
  </div>
<% end %>

app/views/shared/_login_form.html.erb
<%= form_for("user", :url => user_session_path) do |f| %>
  <%= f.text_field :email, :autofocus => true, :placeholder=>"#{User.human_attribute_name(:email)}" %>
  <%= f.password_field :password, :placeholder=>"#{User.human_attribute_name(:password)}" %>
  <%= f.submit(I18n.t(:sign_in), :class => "small radius button") %>
  <div class="row" style="margin: 5px 0px 5px 0px !important;">
    <div class="twelve columns">
      <%= f.check_box :remember_me, :class=> "left" %> <%= f.label :remember_me, User.human_attribute_name(:remember_me), :class => "checkbox" %>
    </div>
  </div>
  <%= link_to I18n.t(:sign_up), new_registration_path("user") %><br />
  <%= link_to I18n.t(:recovery_password), new_password_path("user") %><br />
<% end %>

app/views/shared/_participant_thumb_large.html.erb
<%= image_tag participant.user_avatar.url(:small) %>
<%= participant.user_email %>

app/views/shared/_results.js.erb
$("#results").html("<%= escape_javascript render 'list' %>");