config/routes.rb
Partiude::Application.routes.draw do
  root :to => 'index#index'

  devise_for :users, :path_names => { :sign_in => 'login',
                                      :sign_out => 'logout',
                                      :password => 'recover_password' }

  resources :itineraries, :except => :edit do
    get "search", :on => :collection
  end

  resources :polls, :only => [:create, :view] do
    post "vote", :on => :member
  end

  resources :users, :only => :show
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<div class="row">
		<p>Isso é o que será o rodapé</p>
	</div>
</div>

app/views/layouts/_header_bar.html.erb
<div class="contain-to-grid ">
  <nav class="top-bar">
      <section>
        <%= render :partial => 'layouts/itineraries_links' if current_user.present? %>

        <ul class="right">
          <% if user_signed_in? %>
    <li class="divider"></li>
    <li>
        <%= link_to(I18n.t("devise.sessions.sign_out".to_sym), destroy_user_session_path, :class => "active", :method => :delete) %>
    </li>
<% end %>
          <li class="divider"></li>
          <li class="has-dropdown">
            <a href="/">Partiu.de</a>
            <ul class="dropdown">
              <li><a href="#"><%= I18n.t("partiude.who_we_are".to_sym) %></a></li>
              <li><a href="#"><%= I18n.t("partiude.plans".to_sym) %></a></li>
              <li><a href="#"><%= I18n.t("partiude.partners".to_sym) %></a></li>
              <li><a href="#"><%= I18n.t("partiude.contact".to_sym) %></a></li>
              <li class="divider"></li>
            </ul>
          </li>
        </ul>
      </section>
  </nav>
</div>

app/views/layouts/_itineraries_links.html.erb
<ul class="left">
  <!-- <li class="has-dropdown"><a href="#"><span class="group-name">< @itinerary.name %></span><span class="< @itinerary.transport_type %> selected group-transport"></a>
    <ul class="dropdown">

      <li><a href="#">listar nome dos outros trajetos aqui enzo! /comofas?</a></li>
      <li class="divider"></li>
    </ul>
  </li> -->
  <li class="divider"></li>
  <li>
    <%= link_to(I18n.t(:search_itineraries), search_itineraries_path, :class => "active") %>
  </li>
  <li class="divider"></li>
  <li>
   <%= link_to(I18n.t("itinerary.new".to_sym), new_itinerary_path, :class => "active") %>
  </li>
  <li class="divider"></li>
  <li>
    <%= link_to(I18n.t("itinerary.view_mine".to_sym), itineraries_path, :class => "active") %>
  </li>

  <li class="divider"></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if IE 8]> <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <title>Partiu.de - Trajetos em grupo</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render :partial => 'layouts/header_bar' %>

  <div class="container">
    <% if notice.present? %>
      <div class="alert-box success columns nine centered">
        <p class="notice"><%= notice %></p>
        <a href="" class="close">&times;</a>
      </div>
    <% end %>
    <%= yield %>
  </div>
  <%= render :partial => 'layouts/footer' %>
  <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=true"></script>
  <%= javascript_include_tag "application" %>
  <%= yield :js %>
</body>
</html>